name: env-name-here-does-not-matter
channels:
  - conda-forge
  - bioconda
  - defaults
  - agbiome
  - ursky
  - astrobiomike
  
dependencies:
  - python
  - pip
#quality control
  - bbtools
#  - multiqc
#  - fastqc
#  - trimmomatic
#  - fastp
#assembly
  - spades
  - megahit
  - quast
  - drep
#mapping
#  - bowtie2
#  - minimap2
#binning
  - metabat2
  - binsanity
  - das_tool
  - concoct
#annotation
#  - checkm-genome
#  - blast
#  - prodigal
#  - gtdbtk
#  - gtotree
